openapi: "3.0.0"
info:
  version: 1.0.0
  title: Tasks API
paths:
  /health:
    get:
      summary: Health Check endpoint
      responses:
        200:
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Hello from Lambda!"
        503:
          description: Service is NOT healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Server Error"
  /tasks:
    post:
      summary: Create a new task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: The created task object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    get:
      summary: Retrieve all tasks
      responses:
        200:
          description: An array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        required: true
        description: The ID of the task
        schema:
          type: string
    get:
      summary: Retrieve a task by ID
      responses:
        200:
          description: A task object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Update a task by ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: The updated task object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Delete a task by ID
      responses:
        200:
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Task:
      type: object
      properties:
        taskId:
          type: string
        taskName:
          type: string
        dueDate:
          type: string
        description:
          type: string
        status:
          type: string
